services:

  db:
    image: postgres:17
    volumes:
      - pgdata:/var/lib/postgresql/data/
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_NAME}

  backend:
    build: . # собирает образ
    depends_on: # зависимость от бд
      - db
    ports:
      - 8000:8000
    restart: always
    volumes:
      - .:/app
    env_file:
      - .env

  nginx:
    image: nginx:latest
    ports:
      - 8000:80
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
      - ./static/:/usr/share/html/static
    restart: always
    depends_on:
      - backend

volumes:
  pgdata: