# Generated by Django 5.2 on 2025-04-21 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('todo', 'Ожидает выполнения'), ('in_progress', 'В процессе'), ('done', 'Завершено')], default='todo', max_length=20, verbose_name='Статус'),
        ),
    ]
